spring:
  application:
    name: APi-inventario
  datasource:
    url: jdbc:sqlite:./inventario.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true

jwt:
  secret: ${JWT_SECRET:change-me-change-me-change-me-change-me}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
